title = "gitleaks config"
[allowlist]
  description = "allowlist"
  files = [
    '''.*\.png$''',
    '''.*\.jpg$''',
    '''.*\.lock$'''
  ]
[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(api[_-]?key|token|secret)\s*[:=]\s*['"][A-Za-z0-9_\-]{16,}['"]'''
entropy = 3.5
